### ISSUE TITLE
Adding angular-react-vue templates

### ISSUE THREAD

**Issue by Fiahblade** [chromelyapps/starter-project-templates#1]
Those templates are ready to be added. I was wondering if you want me to add them to this repo and under what file structure. I guess that the cef_downloader is also no longer required (after updating that template as well).

**Comment by mattkol** [comment]
@Fiahblade looks like you have given this more thought than I.  I will take your lead.
Yes the cef_downloader should not be required may be... 
However if you look at the steps:

dotnet new -i "Chromely.CefGlue.Win.Template::*"
dotnet new chromelywin 
dotnet restore
dotnet chromelycef.dll download v66 --cpu=x64 --dest="bin\Debug\netcoreapp2.1"
dotnet build
dotnet run 

The cef download download part comes before the build. The reason I do that is there seem to be an incompatibility between .NET MsBuild and .NET Core build. Because of that the .NET Core is not picking the CPU correctly. So unless we can look closely at this, that trick may stay to avoid downloading cef for wrong CPU.

This is discussed here - https://github.com/chromelyapps/Chromely/issues/66#issuecomment-456249781

Thanks.

**Comment by Fiahblade** [comment]
@mattkol Yes I looked at those steps but after running the new commands, I simply opened the project from Visual Studio which in turn resolved the dependencies automatically. Wasn't aware of the incompatibility issue.

I'm not sure If you are planning to publish these template packages to NuGet as well. But if you are, it would make things even simpler and thus making this repo more of a 'working directory' to store the 'original' template files. Personally I'm pro NuGet but I get that people would prefer cli.

**Comment by mattkol** [comment]
@Fiahblade it is published - [Chromely.CefGlue.Win.Template](https://www.nuget.org/packages/Chromely.CefGlue.Win.Template/)
3 versions so far - and [source code here](https://github.com/chromelyapps/starter-project-templates/tree/master/dotnet-cefglue-cli-template/nuget)
Also has a [steps to create nuget template](https://github.com/chromelyapps/starter-project-templates/blob/master/dotnet-cefglue-cli-template/nuget/Steps%20to%20create%20template.txt) 

I did that for those who want to have a quick go at .NET Core. This is in addition to actual demo projects. I realized the moment developers have this, questions on .NET Core reduced a lot.

But you can take new directions. We do not have to have the cli. Or we make the v66 the last one. Either way I think we are good.

**Comment by Fiahblade** [comment]
Alright great! I'll add the templates, most of the angular-react-vue templates are however using CefSharp. Would you like me to separate them into ..\dotnet-cefglue-cli-template & ..\dotnet-cefsharp-cli-template?
Thanks

**Comment by mattkol** [comment]
@Fiahblade not sure if CefSharp supports .NET Core yet. I doubt it, but one can check. So not sure if CefSharp will play well with .net core cli. When I started the templates, the plan was to include normal Visual Studio project templates too that can be hosted on the [MarketPlace Templates](https://marketplace.visualstudio.com/search?target=VS&category=Templates&vsVersion=&subCategory=All&sortBy=Downloads) and install-able on Visual Studio.

So the folders can be;
For base templates:
..\dotnet-cefglue-cli-template  (cli, .net core) 
..\dotnet-cefsharp-template (VS project template) 
..\dotnet-cefglue-template   (VS project template) 

Extended:
..\dotnet-cefglue-angular-cli-template  (cli, .net core) 
..\dotnet-cefsharp-angular-template (VS project template) 
..\dotnet-cefglue-angular-template   (VS project template) 

.. where "angular" can be replaced with "react" and "vue" for other templates.

I think the base templates are most important, the others are just "nice to have".

Thanks.

**Comment by Fiahblade** [comment]
@mattkol I did some testing and dotnet commands seems to play nicely with the CefSharp templates.

**Comment by mattkol** [comment]
@Fiahblade cool! Wow!!! Did not know that. So will it be correct to move CefSharp to NetStandard? @FrankPfattheicher any comments? 

Is there  a formal statement from CefSharp team on this?

**Comment by Fiahblade** [comment]
@mattkol Ah unfortunately it's still targeting .NET Framework, too bad ;(

**Comment by mattkol** [comment]
@Fiahblade  they may eventually do it for .NET Core 3. So I won't be surprised in the next months.
Thanks.

**Comment by Fiahblade** [comment]
@mattkol Just an update, I think I'm going to hold off on adding those templates. They might require constant updates and fixes to stay relevant. For now I'll focus on the wiki & the demo material. I could always commit to a branch in case you want to take a look or even go ahead and merge them anyways.

**Comment by mattkol** [comment]
@Fiahblade that is great! I think you can go ahead and merge. When I test the latest and I find something I will fix or discuss with you if I need more clarity and vice-versa if merged by me. I am sure @FrankPfattheicher will do that too.

**Comment by Fiahblade** [comment]
@mattkol Alright thanks.

**Comment by mattkol** [comment]
@Fiahblade wow this is nice .. having angular-react-vue cli templates!....will this be uploaded to nuget.org? I think anyone of us can do the upload. I usually use my Microsoft account. Please let me know when to test. Thanks.

**Comment by Fiahblade** [comment]
@mattkol These worked perfectly when I last tested them last week, should be good to be released If I'm not mistaken. ;)

I'd prefer them to be uploaded under your username so that all resources are sort of from an official/credible source (if that makes sense). Or a 'ChromelyApps'-ish account could be setup depending on how you want to manage these packages in the future. All works for me.

**Comment by Fiahblade** [comment]
@mattkol @FrankPfattheicher On a side note, how do you feel about moving the demo files into a separate repository? Or perhaps even a general repo for all demo projects (incl angular-react-vue)?

**Comment by FrankPfattheicher** [comment]
@Fiahblade i feel good with a separate repo...

**Comment by mattkol** [comment]
@Fiahblade me too. Really a great idea.

I have always liked Prism approach - https://github.com/PrismLibrary/Prism-Samples-Wpf
So in our case we can highlight different custom configuration features like - 

Basic Usage
How to set new IOC Container
How to set new logger (or use default)
How to add additional CEF3 command line arguments
How to add custom settings
How to add custom handlers
How to register custom url schemes
How to register custom local resource handlers
How to register custom scheme handlers
How to register custom Javascript objects (Only CefSharp apps)
How to register generic message router handlers (Only CefGlue apps)
How to register Websocket handler (Only CefGlue apps)

Frame Handling (Invoking JavaScript)
CefSharp .NET/JavaScript Integration)
Ajax 
Windows state - Normal, Maximized, Kiosk/Fullscreen modes.

Prism does it in a separate solution - I think that is a good idea because it helps to isolate issues if any occurs. But I am open to other approaches.

**-- may be just about 10 highlights - in separate solution.**

Over time I have written a lot of custom code for testing but I just delete them after testing because I did not want to cluster the demo projects, this is a way to preserve those and easily point developers to samples.

**Comment by Fiahblade** [comment]
@mattkol Yes, I like that highlight repo idea too. Perhaps where the wiki explains you how to do it, those 'highlights' just shows the working end result that you can tinker around with.

Yet that repo wouldn't hold the current demo files right? I guess 2 repo can be made in that case, if that's what you have in mind.

**Comment by mattkol** [comment]
@Fiahblade yes, we are on same page - the wiki explains how, the highlights do "show me the code" that can be modified.

For organization of code, I will take your lead, you have given this a lot more thought than either of us, and we should go with that. As long as developers know there are default settings that do not require writing custom code that can be used straight out of the box.

**Comment by Fiahblade** [comment]
@mattkol Sounds good indeed thanks! It's going to be great, I'm sure of it. :)
